<?php

namespace AppBundle\Repository;

/**
 * HobbyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HobbyRepository extends \Doctrine\ORM\EntityRepository
{
}
